# Generated by Django 3.2.7 on 2021-10-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='work area name')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='Fullname')),
                ('identification', models.CharField(max_length=15, verbose_name='Identification')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('datebirth', models.DateField(verbose_name='Datebirth')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('salary', models.BigIntegerField(verbose_name='Salary')),
                ('work_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='bookstoreApp.workarea')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
