from bookstoreApp.serializers import BaseProductSerializer, BaseProductUpdateSerializer, BaseProductListSerializer, BaseProductUpdateListSerializer
from .productSerializer import ProductSerializer, ProductUpdateSerializer
from .bookSerializer import BookSerializer, BookUpdateSerializer
from .magazineSerializer import MagazineSerializer, MagazineUpdateSerializer
