from .userSerializer import UserSerializer, UserUpdateSerializer
from .employeeSerializer import EmployeeSerializer, EmployeeUpdateSerializer
from .productSerializer import ProductSerializer
from .bookSerializer import BookSerializer
from .magazineSerializer import MagazineSerializer
from .saleSerializer import SaleSerializer
from .reservationSerializer import ReservationSerializer
from .workAreaSerializer import WorkAreaSerializer